import { User, UserRole, InternalManagerType } from '@/shared/types/user';
import { TIME_CONSTANTS } from '@/shared/constants/time';

export const createUsers = (): User[] => {
  return [
    // === ADMIN 권한 사용자들 ===
    {
      id: 'user-1',
      username: 'admin',
      email: 'kim@example.com',
      name: '김철수',
      role: UserRole.ADMIN,
      position: 'IT팀장',
      department: 'IT팀',
      company: 'FLAT',
      profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=admin',
      permissions: ['all'],
      phoneNumber: '010-1234-5678',
      createdAt: new Date(Date.now() - TIME_CONSTANTS.YEAR),
      updatedAt: new Date(Date.now() - TIME_CONSTANTS.YEAR),
      lastLoginAt: new Date(),
      isActive: true,
    },
    {
      id: 'user-5',
      username: 'choi_admin',
      email: 'choi@example.com',
      name: '최동욱',
      role: UserRole.ADMIN,
      position: '시니어 개발자',
      department: '개발팀',
      company: 'FLAT',
      profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=choi_admin',
      permissions: ['all'],
      phoneNumber: '010-5678-9012',
      createdAt: new Date('2024-03-01'),
      updatedAt: new Date('2024-03-01'),
      lastLoginAt: new Date(),
      isActive: true,
    },

    // === INTERNAL_MANAGER (사내 직원들) ===
    {
      id: 'user-2',
      username: 'lee_sales',
      email: 'lee@flat.com',
      name: '이영희',
      role: UserRole.INTERNAL_MANAGER,
      internalManagerType: InternalManagerType.SALES,
      position: '영업 매니저',
      department: '영업팀',
      company: 'FLAT',
      profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=lee_manager',
      permissions: ['projects.manage', 'factories.view', 'users.view'],
      phoneNumber: '010-2345-6789',
      createdAt: new Date(Date.now() - (350 * TIME_CONSTANTS.DAY)),
      updatedAt: new Date(Date.now() - (350 * TIME_CONSTANTS.DAY)),
      lastLoginAt: new Date(),
      isActive: true,
    },
    {
      id: 'user-6',
      username: 'kang_content',
      email: 'kang@flat.com',
      name: '강미나',
      role: UserRole.INTERNAL_MANAGER,
      internalManagerType: InternalManagerType.CONTENT,
      position: '콘텐츠팀 팀장',
      department: '마케팅팀',
      company: 'FLAT',
      profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=kang_manager',
      permissions: ['projects.manage', 'content.manage', 'users.view'],
      phoneNumber: '010-6789-0123',
      createdAt: new Date('2024-01-20'),
      updatedAt: new Date('2024-01-20'),
      lastLoginAt: new Date(),
      isActive: true,
    },
    {
      id: 'user-7',
      username: 'yoon_qa',
      email: 'yoon.qa@flat.com',
      name: '윤품질',
      role: UserRole.INTERNAL_MANAGER,
      internalManagerType: InternalManagerType.QA,
      position: 'QA 매니저',
      department: '품질관리팀',
      company: 'FLAT',
      profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=yoon_qa',
      permissions: ['projects.view', 'schedules.view', 'qa.manage'],
      phoneNumber: '010-7777-8888',
      createdAt: new Date('2024-02-10'),
      updatedAt: new Date('2024-02-10'),
      lastLoginAt: new Date(),
      isActive: true,
    },
    {
      id: 'user-8',
      username: 'lim_container',
      email: 'lim.container@flat.com',
      name: '임용기',
      role: UserRole.INTERNAL_MANAGER,
      internalManagerType: InternalManagerType.CONTAINER,
      position: '용기 담당자',
      department: '생산관리팀',
      company: 'FLAT',
      profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=lim_container',
      permissions: ['projects.view', 'container.manage'],
      phoneNumber: '010-8901-2345',
      createdAt: new Date('2024-02-20'),
      updatedAt: new Date('2024-02-20'),
      lastLoginAt: new Date(),
      isActive: true,
    },
    {
      id: 'user-15',
      username: 'song_ra',
      email: 'song.ra@flat.com',
      name: '송규제',
      role: UserRole.INTERNAL_MANAGER,
      internalManagerType: InternalManagerType.RA,
      position: 'RA 담당자',
      department: '법무팀',
      company: 'FLAT',
      profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=song_ra',
      permissions: ['projects.view', 'regulatory.manage'],
      phoneNumber: '010-1111-2222',
      createdAt: new Date('2024-01-15'),
      updatedAt: new Date('2024-01-15'),
      lastLoginAt: new Date(),
      isActive: true,
    },
    {
      id: 'user-16',
      username: 'kim_general_manager',
      email: 'kim.gm@flat.com',
      name: '김총무',
      role: UserRole.INTERNAL_MANAGER,
      position: '총무팀장',
      department: '총무팀',
      company: 'FLAT',
      profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=kim_general_manager',
      permissions: ['projects.manage', 'users.manage', 'factories.manage'],
      phoneNumber: '010-3333-4444',
      createdAt: new Date('2024-01-10'),
      updatedAt: new Date('2024-01-10'),
      lastLoginAt: new Date(),
      isActive: true,
    },

    // === EXTERNAL_MANAGER (공장 담당자들) ===
    {
      id: 'user-3',
      username: 'park_factory',
      email: 'park.factory@cosmetech.com',
      name: '박공장',
      role: UserRole.EXTERNAL_MANAGER,
      factoryId: 'factory-1', // 코스메테크
      position: '공장장',
      department: '생산관리팀',
      company: '코스메테크',
      profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=park_factory',
      permissions: ['factory.manage', 'projects.view', 'schedules.manage'],
      phoneNumber: '010-3333-4444',
      createdAt: new Date(Date.now() - (330 * TIME_CONSTANTS.DAY)),
      updatedAt: new Date(Date.now() - (330 * TIME_CONSTANTS.DAY)),
      lastLoginAt: new Date(),
      isActive: true,
    },
    {
      id: 'user-4',
      username: 'jung_factory',
      email: 'jung.factory@beautytech.com',
      name: '정생산',
      role: UserRole.EXTERNAL_MANAGER,
      factoryId: 'factory-2', // 뷰티테크
      position: '생산 관리자',
      department: '생산팀',
      company: '뷰티테크',
      profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jung_factory',
      permissions: ['factory.manage', 'projects.view', 'schedules.view'],
      phoneNumber: '010-4444-5555',
      createdAt: new Date(Date.now() - (315 * TIME_CONSTANTS.DAY)),
      updatedAt: new Date(Date.now() - (315 * TIME_CONSTANTS.DAY)),
      lastLoginAt: new Date(),
      isActive: true,
    },
    // === CUSTOMER (고객사 담당자들) ===
    {
      id: 'user-9',
      username: 'park_amorepacific',
      email: 'park.ms@amorepacific.com',
      name: '박민수',
      role: UserRole.CUSTOMER,
      position: '구매팀장',
      department: '구매팀',
      company: '아모레퍼시픽',
      profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=park_amorepacific',
      permissions: ['projects.view'],
      phoneNumber: '010-3456-7890',
      createdAt: new Date('2024-01-20'),
      updatedAt: new Date('2024-01-20'),
      lastLoginAt: new Date(),
      isActive: true,
    },
    {
      id: 'user-10',
      username: 'jung_lgcare',
      email: 'jung.sj@lgcare.com',
      name: '정수진',
      role: UserRole.CUSTOMER,
      position: '제품개발 과장',
      department: '제품개발팀',
      company: 'LG생활건강',
      profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jung_lgcare',
      permissions: ['projects.view'],
      phoneNumber: '010-4567-8901',
      createdAt: new Date('2024-02-25'),
      updatedAt: new Date('2024-02-25'),
      lastLoginAt: new Date(),
      isActive: true,
    },
    {
      id: 'user-11',
      username: 'yoon_cosmax',
      email: 'yoon.sj@cosmax.com',
      name: '윤서준',
      role: UserRole.CUSTOMER,
      position: '연구소장',
      department: 'R&D센터',
      company: '코스맥스',
      profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=yoon_cosmax',
      permissions: ['projects.view'],
      phoneNumber: '010-7890-1234',
      createdAt: new Date('2024-03-15'),
      updatedAt: new Date('2024-03-15'),
      lastLoginAt: new Date(),
      isActive: true,
    },
    {
      id: 'user-12',
      username: 'lim_kolmar',
      email: 'lim.hn@kolmar.co.kr',
      name: '임하나',
      role: UserRole.CUSTOMER,
      position: '마케팅 차장',
      department: '마케팅팀',
      company: '콜마비앤에이치',
      profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=lim_kolmar',
      permissions: ['projects.view'],
      phoneNumber: '010-8901-2345',
      createdAt: new Date('2024-02-28'),
      updatedAt: new Date('2024-02-28'),
      lastLoginAt: new Date(),
      isActive: true,
    },
    {
      id: 'user-13',
      username: 'han_welcos',
      email: 'han.sy@welcos.co.kr',
      name: '한세영',
      role: UserRole.CUSTOMER,
      position: '브랜드 매니저',
      department: '브랜드팀',
      company: '웰코스',
      profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=han_welcos',
      permissions: ['projects.view'],
      phoneNumber: '010-9876-5432',
      createdAt: new Date('2024-03-01'),
      updatedAt: new Date('2024-03-01'),
      lastLoginAt: new Date(),
      isActive: true,
    },
    {
      id: 'user-14',
      username: 'cho_innisfree',
      email: 'cho.jy@innisfree.com',
      name: '조자연',
      role: UserRole.CUSTOMER,
      position: '제품기획자',
      department: '기획팀',
      company: '이니스프리',
      profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=cho_innisfree',
      permissions: ['projects.view'],
      phoneNumber: '010-1122-3344',
      createdAt: new Date('2024-02-15'),
      updatedAt: new Date('2024-02-15'),
      lastLoginAt: new Date(),
      isActive: true,
    },
    {
      id: 'user-17',
      username: 'kim_tonymoly',
      email: 'kim.jh@tonymoly.co.kr',
      name: '김지현',
      role: UserRole.CUSTOMER,
      position: 'PM',
      department: '제품개발팀',
      company: '토니모리',
      profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=kim_tonymoly',
      permissions: ['projects.view'],
      phoneNumber: '010-2468-1357',
      createdAt: new Date('2024-03-10'),
      updatedAt: new Date('2024-03-10'),
      lastLoginAt: new Date(),
      isActive: true,
    },
    {
      id: 'user-18',
      username: 'lee_thefaceshop',
      email: 'lee.mj@thefaceshop.com',
      name: '이민정',
      role: UserRole.CUSTOMER,
      position: '구매 담당자',
      department: '구매팀',
      company: '더페이스샵',
      profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=lee_thefaceshop',
      permissions: ['projects.view'],
      phoneNumber: '010-1357-2468',
      createdAt: new Date('2024-02-10'),
      updatedAt: new Date('2024-02-10'),
      lastLoginAt: new Date(),
      isActive: true,
    },
  ];
};